apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployment.name}}
  labels:
    app: superapp
    sucks: {{.Values.deployment.name}} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superapp
      sucks: {{.Values.deployment.name}}       
  template:
    metadata:
       labels: 
         app: superapp
         sucks: {{.Values.deployment.name}} 
    spec:
      containers: 
        - name: superapp
          image: "{{ .Values.image.name }}"
          ports: 
            - containerPort: 8080